config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users

  resources :contacts
  
  devise_scope :user do
    authenticated :user do
      root 'contacts#index', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end
  
  root 'devise/sessions#new'

end

app/models/contact.rb
class Contact < ActiveRecord::Base
  has_many :addresses, dependent: :destroy
  has_many :phones, dependent: :destroy
  belongs_to :user
    
  validates :first_name, :user_id, presence: :true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i, on: [:create, :update] } , allow_blank: true
  
  accepts_nested_attributes_for :addresses, allow_destroy: true, :reject_if => lambda { |a| a[:address1].blank? && a[:address2].blank? && a[:city].blank? && a[:state].blank? && a[:zip].blank? }
  accepts_nested_attributes_for :phones, allow_destroy: true, :reject_if => lambda { |a| a[:number].blank? }
  
  def name
    "#{first_name} #{last_name}"
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  load_and_authorize_resource
  before_action :set_contact, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  
  
  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.where(user_id: current_user.id).order(sort_column + " " + sort_direction)
  end 

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
    1.times { @contact.addresses.build }
    1.times { @contact.phones.build }
  end

  # GET /contacts/1/edit
  def edit
    if @contact.addresses.empty?
      1.times { @contact.addresses.build }
    end
    
    if @contact.phones.empty?
      1.times { @contact.phones.build }
    end
    
    
  end

  # POST /contacts
  # POST /contacts.json
  def create
    contact_params[:user_id] = current_user
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        1.times { @contact.addresses.build }
        1.times { @contact.phones.build }
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        1.times { @contact.addresses.first }
        1.times { @contact.phones.first }        
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: "#{@contact.name} was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
  
    def sort_column
      Contact.column_names.include?(params[:sort]) ? params[:sort] : "last_name"
    end
    
    def sort_direction
      %w[asc desc].include?(params[:direction])? params[:direction] : 'asc'
    end
  
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:first_name, :last_name, :email, :user_id, phones_attributes: [:id, :number, :phone_type_id, :_destroy], addresses_attributes: [:id, :address1, :address2, :city, :state, :zip, :_destroy])
    end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/views/contacts/_address.html.erb
<%= f.fields_for :addresses do |addresses_form| %>
  <br/>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Address</h3>
    </div>    
    <div class="panel-body">
      <div class="control-group">
        <%= addresses_form.label :address1, :class => 'control-label' %>
        <div class="controls">
          <%= addresses_form.text_field :address1, :class => 'form-control' %>
        </div>
      </div>
      <div class="control-group">
        <%= addresses_form.label :address2, :class => 'control-label' %>
        <div class="controls">
          <%= addresses_form.text_field :address2, :class => 'form-control' %>
        </div>
      </div>
      <div class="control-group">
        <%= addresses_form.label :city, :class => 'control-label' %>
        <div class="controls">
          <%= addresses_form.text_field :city, :class => 'form-control' %>
        </div>
      </div>
      <div class="control-group">
        <%= addresses_form.label :state, :class => 'control-label' %>
        <div class="controls">
          <%= addresses_form.text_field :state, :class => 'form-control' %>
        </div>
      </div>
      <div class="control-group">
        <%= addresses_form.label :zip, :class => 'control-label' %>
        <div class="controls">
          <%= addresses_form.text_field :zip, :class => 'form-control' %>
        </div>
      </div>    
      <div class="control-group">
        <div class="controls">
          <%= addresses_form.check_box :_destroy %>
          <%= addresses_form.label :_destroy, "Delete Address" %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/_form.html.erb
<%= form_for @contact, :html => { :class => "form-horizontal contact" } do |f| %>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Contact Information</h3>
    </div>    
    <div class="panel-body">
      <% if @contact.errors.any? %>
        <div id="error_expl" class="panel panel-danger">
          <div class="panel-heading">
            <h3 class="panel-title"><%= pluralize(@contact.errors.count, "error") %> prohibited this contact from being saved:</h3>
          </div>
          <div class="panel-body">
            <ul>
            <% @contact.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
            </ul>
          </div>
        </div>
      <% end %>
      <%= f.hidden_field :user_id, :value => current_user.id %>
      <div class="control-group">
        <%= f.label :first_name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :first_name, :class => 'form-control' %>
        </div>
        <%= error_span(@contact[:first_name]) %>
      </div>
      <div class="control-group">
        <%= f.label :last_name, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :last_name, :class => 'form-control' %>
        </div>
        <%= error_span(@contact[:last_name]) %>
      </div>
      <div class="control-group">
        <%= f.label :email, :class => 'control-label' %>
        <div class="controls">
          <%= f.text_field :email, :class => 'form-control' %>
        </div>
        <%= error_span(@contact[:email]) %>
      </div>      
    </div>
  </div>      
    
  <%= render :partial => "address", :locals => { :f => f } %>
  
  <%= render :partial => "phone", :locals => { :f => f } %>
  
  <br/>

  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            contacts_path, :class => 'btn btn-default' %>

<% end %>

app/views/contacts/_phone.html.erb
<%= f.fields_for :phones do |phones_form| %>
  <br/>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h3 class="panel-title">Phone Numbers</h3>
    </div>    
    <div class="panel-body">
      <div class="control-group">
        <%= phones_form.label :number, :class => 'control-label' %>
        <div class="controls">
          <%= phones_form.text_field :number, :class => 'form-control' %>
        </div>
      </div>
      <div class="control-group">
        <%= phones_form.label :phone_type, :class => 'control-label' %>
        <div class="controls">
          <%= phones_form.collection_select :phone_type_id, PhoneType.all, :id, :name, {prompt: "Select a Phone Type"}, {class: "form-control"} %>
          <%= phones_form.check_box :_destroy %>
          <%= phones_form.label :_destroy, "Delete Phone Number" %>          
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contacts/index.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-hover">
  <thead>
    <tr>
      <th><%= sortable "last_name", model_class.human_attribute_name(:name) %></th>
      <th><%= sortable "email", model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:phone) %></th>
      <th><%= model_class.human_attribute_name(:address) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% unless @contacts.blank? %>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= link_to contact.name, edit_contact_path(contact) %></td>
          <% if contact.email.blank? %>
            <td></td>
          <% else %>
            <td><%= link_to contact.email, edit_contact_path(contact) %></td>
          <% end %>
        <td>
          <% contact.phones.each do |phone| %>
            <%= phone.number %>
          <% end %>
        </td>
        <td>
          <% contact.addresses.each do |address| %>
            <%= address.address1 %>
          <% end %>
        </td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_contact_path(contact), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      contact_path(contact),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_contact_path,
            :class => 'btn btn-primary' %>

app/views/contacts/new.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/contacts/show.html.erb
<%- model_class = Contact -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:first_name) %>:</strong></dt>
  <dd><%= @contact.first_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:last_name) %>:</strong></dt>
  <dd><%= @contact.last_name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @contact.email %></dd>  
  <% unless @contact.addresses.blank? %>
    <% @contact.addresses.each do |address| %>
      <dt><strong><%= model_class.human_attribute_name(:address1) %>:</strong></dt>
      <dd><%= address.address1 %></dd>
      <dt><strong><%= model_class.human_attribute_name(:address2) %>:</strong></dt>
      <dd><%= address.address2 %></dd>
      <dt><strong><%= model_class.human_attribute_name(:city) %>:</strong></dt>
      <dd><%= address.city %></dd>
      <dt><strong><%= model_class.human_attribute_name(:state) %>:</strong></dt>
      <dd><%= address.state %></dd>
      <dt><strong><%= model_class.human_attribute_name(:zip) %>:</strong></dt>
      <dd><%= address.zip %></dd>
    <% end %>
  <% end %>
  
  <% unless @contact.phones.blank? %>
    <% @contact.phones.each do |phone| %>
      <dt><strong><%= model_class.human_attribute_name(:phone) %></strong></dt>
      <dd><%= phone.number %></dd>
    <% end %>
  <% end %>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              contacts_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_contact_path(@contact), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              contact_path(@contact),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>